#!/bin/sh
module="LKHP"
device="lkhp"
mode="600"

# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
#/sbin/insmod -f ./$module.o $* || exit 1
/sbin/insmod ./$module.o $* || exit 1

major=`cat /proc/devices | awk "\\$2==\"$device\" {print \\$1}"`

echo "major = $major"

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's lkhp that has several devices in it.

rm -f /dev/$device
mknod /dev/$device c $major 0
chgrp $group /dev/$device
chmod $mode  /dev/$device

